export const imgData = [
  {
    name: 'Image',
    path: '../../assets/image.png',
    isClassified: true,
    isSelected: false
  }, {
    name: 'Image',
    path: '../../assets/image.png',
    isClassified: true,
    isSelected: false
  }, {
    name: 'Image',
    path: '../../assets/image.png',
    isClassified: true,
    isSelected: false
  }, {
    name: 'Image',
    path: '../../assets/image.png',
    isClassified: true,
    isSelected: false
  }, {
    name: 'Image',
    path: '../../assets/image.png',
    isClassified: true,
    isSelected: false
  }, {
    name: 'Image',
    path: '../../assets/image.png',
    isClassified: true,
    isSelected: false
  }, {
    name: 'Image',
    path: '../../assets/image.png',
    isClassified: true,
    isSelected: false
  }, {
    name: 'Image',
    path: '../../assets/image.png',
    isClassified: true,
    isSelected: false
  }, {
    name: 'Image',
    path: '../../assets/image.png',
    isClassified: true,
    isSelected: false
  }, {
    name: 'Image',
    path: '../../assets/image.png',
    isClassified: true,
    isSelected: false
  }, {
    name: 'Image',
    path: '../../assets/image.png',
    isClassified: true,
    isSelected: false
  }, {
    name: 'Image',
    path: '../../assets/image.png',
    isClassified: true,
    isSelected: false
  }
];
