//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIndexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchExtraction
    {
        public int Batchextractionid { get; set; }
        public Nullable<int> Batchid { get; set; }
        public Nullable<int> DocumenttypeId { get; set; }
        public string DocumenttypeName { get; set; }
        public string Batchpath { get; set; }
        public string JsonString { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> ConcatString { get; set; }
    }
}
