//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIndexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Clientid { get; set; }
        public string Clientname { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<decimal> Zip { get; set; }
        public Nullable<decimal> Pointofcontact1 { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<decimal> Pointofcontact2 { get; set; }
        public Nullable<decimal> Phonenumber { get; set; }
        public string Emailid { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
    }
}
