//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIndexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cst_DocTypes
    {
        public int Cst_DocTypeID { get; set; }
        public string DocTypeName { get; set; }
        public Nullable<int> MinPages { get; set; }
        public Nullable<int> MaxPages { get; set; }
        public Nullable<decimal> Percentageofsimilarity { get; set; }
        public string AddIfPrevTypeisSame { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string HavingPageNumbers { get; set; }
        public string PageNumberFormat { get; set; }
        public Nullable<int> Cst_DocNameID { get; set; }
        public string FileName { get; set; }
    }
}
