//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIndexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cst_Keywords
    {
        public int Cst_KeywordID { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> Cst_DocTypeID { get; set; }
        public Nullable<decimal> Thresholdpercetage { get; set; }
        public string ZoneArea { get; set; }
        public Nullable<bool> Casesensitive { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string PagePosition { get; set; }
        public string HasLastKeywords { get; set; }
    }
}
