//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIndexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cst_DocName
    {
        public int Cst_DocNameID { get; set; }
        public string DocName { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createddatetime { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddatetime { get; set; }
    }
}
