//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIndexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtractionConfig
    {
        public int ExtractionConfigID { get; set; }
        public Nullable<int> Cst_DocTypeID { get; set; }
        public string ExtractionType { get; set; }
        public Nullable<int> Pageindex { get; set; }
        public string FieldName { get; set; }
        public string FieldDataCordinates { get; set; }
        public string Anchor { get; set; }
        public string AnchorDataCordinates { get; set; }
        public string Brules { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public Nullable<int> LEFT { get; set; }
        public Nullable<int> TOP { get; set; }
        public Nullable<int> RIGHT { get; set; }
        public Nullable<int> BOTTOM { get; set; }
        public Nullable<int> OCRHeight { get; set; }
        public Nullable<int> OCRWidth { get; set; }
        public string AnchorCoordinates { get; set; }
        public Nullable<int> ALEFT { get; set; }
        public Nullable<int> ATOP { get; set; }
        public Nullable<int> ARIGHT { get; set; }
        public Nullable<int> ABOTTOM { get; set; }
    }
}
