//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIndexDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMARTINDEXEntities : DbContext
    {
        public SMARTINDEXEntities()
            : base("name=SMARTINDEXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classification> Classifications { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Lob> Lobs { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StatesMaster> StatesMasters { get; set; }
        public virtual DbSet<ZipCodeMaster> ZipCodeMasters { get; set; }
        public virtual DbSet<BatchExtraction> BatchExtractions { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Cst_Keywords> Cst_Keywords { get; set; }
        public virtual DbSet<Cst_DocTypes> Cst_DocTypes { get; set; }
        public virtual DbSet<ClientMappingDocType> ClientMappingDocTypes { get; set; }
        public virtual DbSet<BatchAudit> BatchAudits { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<BatchAutoExtraction> BatchAutoExtractions { get; set; }
        public virtual DbSet<Cst_DocName> Cst_DocName { get; set; }
        public virtual DbSet<ExtractionConfig> ExtractionConfigs { get; set; }
    }
}
