//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIndexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipCodeMaster
    {
        public int ZipCodeId { get; set; }
        public string Zip { get; set; }
        public string Type { get; set; }
        public string Primary_City { get; set; }
        public string Acceptable { get; set; }
        public string Unacceptable_Cities { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string Timezone { get; set; }
        public string Area_Codes { get; set; }
        public Nullable<int> Latitude { get; set; }
        public Nullable<int> Longitude { get; set; }
        public string World_Region { get; set; }
        public string Country { get; set; }
        public Nullable<int> Decommissioned { get; set; }
        public Nullable<int> Estimated_Population { get; set; }
        public string Notes { get; set; }
    }
}
